### GET/

GET http://localhost:1998




###
POST http://localhost:1998/auth/register
Content-Type: application/json

{
    "username":"chyewewe@gmail.com",
    "password":"121121sdsdsd"
}


###

POST http://localhost:1998/auth/login
Content-Type: application/json

{
     "username":"chyewewe@gmail.com",
    "password":"121121sdsdsd"

}